### ISSUE TITLE
Reloading scripts

### ISSUE THREAD

**Issue by esciara** [home-assistant-tutorials/03.hello-world-card-plus#2]
Thank you for your tutorial. Very helpful !

On tutorial 03, you write : 

> If you change the code in card.js for testing, you may have difficulties to reload it. In this case it may help, to directly reload the script and check, that it has been updated.

Can you explain how you `directly reload the script` ?

**Comment by elmar-hinz** [comment]
Hello,

in short figure out the URL of the script and paste it into the URL field of your browser. The Browser should show the source code of the script and you can force reload it this way. Once the browser has updated the script in one window, the reload should work in other windows, too. 

This is not very comfortable, but sometimes the solution.

**Comment by esciara** [comment]
Such a bummer... indeed by going to http://localhost:8123/local/02.hello-world-card/card.js and refreshing that url, the card updated. I can't image their would not be a more automated version of this, but could not find anything anywhere.

Thanks for the tip.

**Comment by elmar-hinz** [comment]
Just what I thought. They have to go a long way to prevent browsers from reloading and even force reloading the scripts.
